language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      dist: xenial
      env:
        - CC=clang-7
        - CXX=clang++-7
        - CC_FOR_BUILD=clang-7
        - CXX_FOR_BUILD=clang++-7
        - LD=lld-7
      before_script:
        - curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install clang-7 lld-7 -y
      script:
        - sudo mv /usr/bin/ld /usr/bin/ld.old && sudo ln -s /usr/bin/lld-7 /usr/bin/ld
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
        - make -j4
        - ../tools/tests/test_runner.py -b . -d tests -s ../tests


    - os: linux
      dist: xenial
      compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
        - CC_FOR_BUILD=gcc-8
        - CXX_FOR_BUILD=g++-8
        - LD=ld
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
        - make -j4
        - ../tools/tests/test_runner.py -b . -d tests -s ../tests


    - os: osx
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON ..
        - make -j4
        - ../tools/tests/test_runner.py -b . -d tests -s ../tests


    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - BUILD_TOOL=xcodebuild
      before_script:
        - gem install xcpretty
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DJET_LIVE_BUILD_TESTS=ON -G Xcode ..
        - xcodebuild -alltargets -quiet
        - ../tools/tests/test_runner.py -b . -d tests/Debug -s ../tests
